version: '3.7'

services:
  app:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub-cms
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    networks:
      - public
    configs:
      - source: bbnavi-datahub-cms-master-key
        target: /app/config/master.key
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.frontend.rule: Host:cms.bbnavi.de
      restart_policy:
        condition: on-failure

volumes:
  unicorn:
  assets:

configs:
  bbnavi-datahub-cms-master-key:
    external: true

networks:
  public:
    external: true
